### ISSUE TITLE
Linear layer sizes

### ISSUE THREAD

**Issue by ClintFeher** [tianchen101/MQRNN#1]
Hi there
I was looking at the Global Encoder implementation:
self.linear1 = nn.Linear(in_features= hidden_size + covariate_size*horizon_size, 
                                out_features= horizon_size*hidden_size*3)
        
self.linear2 = nn.Linear(in_features= horizon_size*hidden_size*3, 
                        out_features= horizon_size*hidden_size*2)

self.linear3 = nn.Linear(in_features= horizon_size*hidden_size*2, 
                        out_features= (horizon_size+1)*context_size)

I was wondering why do you multiply by 3 the out features in the first layer, then by 2 in the second layer ? I didn't see any reference to this in the article.

Thanks, your implementation is very helpful to understanding the article.
Clint Feher

**Comment by tianchen101** [comment]
Hi,

You are right that the MLP part is not covered in detail in the original paper. I took a look at the implementation of this model in AWS gluon, and from what I see there, the MLP part can be configured by user( in terms of number of layers and units per layer), so for simplicity I chose this structure for testing purpose.

Hope this helps,
Xinghang

**Comment by Flying7514** [comment]
问一下这个是MQRNN官方提供的源代码吗？

**Comment by Flying7514** [comment]
感觉localdecoder的输出激活函数有问题，第二个激活函数导致输出全为正
def forward(self,input):
        layer1_output = self.linear1(input)
        layer1_output = self.activation(layer1_output)

        layer2_output = self.linear2(layer1_output)
        layer2_output = self.activation(layer2_output)
        return layer2_output

**Comment by tianchen101** [comment]
The activation function is intended to using RELU, because this is used for prediction in inventory, demand etc which is not allowed to be negative number.
